In [50]:
import polars as pl
from haystack import Document
from haystack.components.evaluators import DocumentNDCGEvaluator, DocumentMAPEvaluator, DocumentRecallEvaluator
from haystack.components.evaluators.document_recall import RecallMode

from app.word2vec.pipeline import create as create_w2v
from app.sbert.pipeline import create as create_sbert
from app.llm.pipeline import create as create_llm

In [48]:
datasets = pl.read_csv("./data/fyp.csv") \
    .filter(pl.col("abstract").is_not_null()) \
    .unique("title")
datasets

shape: (4_389, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ title                  ┆ abstract               ┆ webpage_url            ┆ document_url          │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ str                    ┆ str                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ A Study on the         ┆ Building Information   ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Efficiency of t…       ┆ Modelling…             ┆ du.my/23…              ┆ edu.my/23…            │
│ Industrialized         ┆ IBS (Industrialized    ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Building System…       ┆ Building S…            ┆ du.my/91…              ┆ edu.my/91…            │
│ Design and Fabrication ┆ This project was       ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ of a No…               ┆ initially con…         ┆ du.my/96…              ┆ edu.my/96…            │
│ Impact of Jet Fuel     ┆ This study attempts to ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Price on th…           ┆ investi…               ┆ du.my/18…              ┆ edu.my/18…            │
│ Standardize            ┆ In continuous inkjet   ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Troubleshooting Sy…    ┆ technolog…             ┆ du.my/98…              ┆ edu.my/98…            │
│ …                      ┆ …                      ┆ …                      ┆ …                     │
│ In Vitro Antagonism    ┆ Elaeis guineensis or   ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Activity o…            ┆ commonly …             ┆ du.my/22…              ┆ edu.my/22…            │
│ Peanut Butter Matrix   ┆ Probiotics-rich foods  ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ as a Pote…             ┆ are incr…              ┆ du.my/25…              ┆ edu.my/25…            │
│ Tomato Grading System  ┆ Nowadays, consumer     ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ by Image…              ┆ demand more…           ┆ du.my/14…              ┆ edu.my/14…            │
│ Malay Part-Of-Speech   ┆ The existence of       ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ (POS) Tag…             ┆ part-of-speec…         ┆ du.my/22…              ┆ edu.my/22…            │
│ The Influence of       ┆ The beauty industry is ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Social Media …         ┆ one of …               ┆ du.my/28…              ┆ edu.my/28…            │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [49]:
documents = [Document(id=row["title"], content=row["abstract"]) for row in datasets.iter_rows(named=True)]
documents

[Document(id=A Study on the Efficiency of the Implementation of Building Information Modelling (BIM) in the Construction Industry, content: 'Building Information Modelling (BIM) is a technology that is currently gaining momentum within the c...'),
 Document(id=Industrialized Building System (IBS) in Malaysia Construction Industry, content: 'IBS (Industrialized Building System) is defined as a construction system which all the components ma...'),
 Document(id=Design and Fabrication of a Non-Electrical Driven Positive Displacement Pump, content: 'This project was initially conceived to be a solar-powered water pump with the aim of transporting w...'),
 Document(id=Impact of Jet Fuel Price on the Returns of Airlines Stock Price in ASEAN-5, content: 'This study attempts to investigate the impact of the jet fuel price on the returns on the airline st...'),
 Document(id=Standardize Troubleshooting System For An Ink Jet Printer Servicing Company, content: 'In continuous inkjet technology, a high-pressure pump directs liquid ink from a reservoir through a ...'),
 Document(id=Investigate the Impact on Deploying Photovoltaic Panel Roof against Indoor Temperature, content: 'Solar panel or photo-voltaic module, is an assembly of PV cells mounted in a framework for installat...'),
 Document(id=The Exchange Rates and the Malaysia Economy, content: 'Over the decades, policymakers and economists from Malaysia have examined the economic factors that ...'),
 Document(id=Factors to Consider to Buy a House, content: 'This research is about studying in the factors of affecting the decision making of house purchasing....'),
 Document(id=Evaluation of Antibacterial Efficacy of Some Alcohol-Based Hand Sanitizers, Hand Soaps and Disinfectants, content: 'Due to the current pandemic, people are urged to maintain hand hygiene to prevent the spread of infe...'),
 Document(id=A Study on the Effect of Calcium Carbonate and Sodium Sulfate Modification on Improving Properties of Soy Protein Adhesive Fiber Board, content: 'Adhesive is very important when it is used to produce a fiber/particle board. Natural adhesive is ge...'),
 Document(id=Antioxidative, Anti Inflammatory and Cytotoxic Effects of Standardized Papaya Leaves Fraction, content: 'The Carica papaya Linn. leaves fractions were proven to have therapeutic application in the manageme...'),
 Document(id=Smart Dustbin, content: 'The Smart Dustbin is designed for improving hygiene and ensuring regular waste disposal, resulting i...'),
 Document(id=The Political Socialization of First-time Voters after Malaysia’s Amendment on Voting Age, content: 'Pakatan Harapan had complied with one of their manifestoes during the 14th General Election in Malay...'),
 Document(id=Mobile Chat Application with High-Level Messaging API based on Decentralized Networks, content: 'The main purpose of this project is to develop a system that is able to send messages via decentrali...'),
 Document(id=A Case Study on Building Defects and Risk at Old Residential Building, content: 'Building defects have become commonplace in Malaysia's construction landscape, often met with indiff...'),
 Document(id=Contractor Safety Management Practices in Malaysian Construction Projects, content: 'The Malaysian construction industry records some of the highest accident and fatality rates, with co...'),
 Document(id=Extraction of Antioxidative Phenolic Compounds from Spent Coffee Ground, content: 'This study was conducted to investigate the effects of different pretreatment methods on the extract...'),
 Document(id=Evaluation of BIM Education for Quantity Surveying Programmes in Higher Education Institutions (HEIs), content: 'Building Information Modelling (BIM) has been introduced to the construction industry of Malaysia fo...'),
 Document(id=CareForYou Clinic Administration System, content: 'Some clinics still rely on traditional, non-computerized methods to manage operations, creating sign...'),
 Document(id=Napping, Sleep Quality and Psychological Well-Being: a Comparison Study between Athletes and Non-Athletes, content: 'The objective of this study is to investigate sleep quality, difference in napping behavior and psyc...'),
 Document(id=The Influences of Gender of Public Relations Practitioners on Their Career Advancement Opportunities, content: 'This research aims to find out the perspective of public relations practitioners on the influences o...'),
 Document(id=Resume Credentials Extraction, content: 'Resume parsing or resume information extraction is the most time-consuming task in the hiring and po...'),
 Document(id=Determination of Benzoic Acid in Commercial Fermented Soybean Pastes via Ultraviolet-Visible Spectroscopy (UV-Vis) and Reversed-Phase High Performance Liquid Chromatography (RP-HPLC) Methods, content: 'Fermented soybean paste is a product which undergone brine fermentation by Aspergillus species and c...'),
 Document(id=Innovative Food Product Development of Mini Snow Skin Hawthorn Moon Cake, content: 'Hawthorn (Crataegus spp.) fruits are increasingly used as raw ingredient for nutraceuticals and func...'),
 Document(id=Design and Development of Facial Recognition System of Indoor Images, content: 'Nowadays, Facial Recognition System is very common and it is a type of computer application that can...'),
 Document(id=The Impact of the Audience on the Survival of Malaysian Youtubers, content: 'With the continuous development of technologies and the Internet, the rapid changes in trends and au...'),
 Document(id=The Impacts of Social Media Usage on Academic Performance among TAR UC Students, content: 'With continuous development of technologies and the Internet, the rapid advancement of information a...'),
 Document(id=Design and Fabrication of Flow Visualization Table, content: 'The purpose of this project is to develop a water table for educational and research aspect. From th...'),
 Document(id=From Entertainment to Empowerment: Exploring Personal Growth and Female Empowerment in Miley Cyrus and Adele's Albums through the Personal Growth Process (PGP) Model, content: 'This study investigates the portrayal of personal growth and its contribution to female empowerment ...'),
 Document(id=Digital Technology in Real Estate Transactions, content: 'The “Digital Technology in Real Estate Transactions” study examines the adoption of technology in th...'),
 Document(id=Contribution of Small and Medium Enterprise (SMEs) to Malaysia’s Economy, content: 'This study investigates the contribution of Small and Medium Enterprises (SMEs) to Malaysia’s econom...'),
 Document(id=The Impact of Exchange Rate Fluctuation on International Trade between Malaysia and China, content: 'This study identifies the impact of exchange rate fluctuation on international  trade between Malays...'),
 Document(id=Roadside RGB LED Matrix Advertisement Board by Using MBED Microcontroller, content: 'This project is aimed to develop a digital type of advertisement board namely Roadside RGB LED Matri...'),
 Document(id=Biomechanical Analysis of Lateral Movements in Casual Badminton Player, content: 'Badminton is one of the most popular sports around the globe. It is a sport that demands strong phys...'),
 Document(id=Design and Simulation Compliance Mechanism for Lower Extremities Exoskeleton, content: 'Lower limb extremity exoskeleton can be said to have two main objectives which is the rehabilitation...'),
 Document(id=Effects of Monk Fruit Sweetener on the Physicochemical, Microbiological and Sensory Properties of Strawberry Frozen Yogurt, content: 'This study investigated the effects of monk fruit sweetener (MFS) as natural sugar substitute on the...'),
 Document(id=To Study the Effect of Green Filler-Eggshell on Polyethylene and Natural Rubber, content: 'The objective of this project is to study the effect of adding eggshell powder (ESP) into polyethyle...'),
 Document(id=Design and Fabrication of a Lifting Device for Patient, content: 'The dissertation is to design and fabricate of a lifting device for patient. In Malaysia, care taker...'),
 Document(id=Effect of COVID-19 Pandemic to Productivity of Small and Medium Sized Construction Firms, content: 'Global outbreak of COVID-19 significantly impacted the construction activities in the form of disrup...'),
 Document(id=The Integration of SCADA and PLCs in FMS 200 with Standard Industrial Communication Protocol and Networking, content: 'This dissertation is about the integration of SCADA and PLCs in FMS 200 with standard industrial com...'),
 Document(id=Network Performance Benchmark between Open VSwitch (OVS) and Native VXLAN Implementation in a Cloud Based Virtual Extensible LAN (VXLAN) Network, content: 'The majority research related to cloud computing infrastructure has focused on the communication bet...'),
 Document(id=A study to evaluate the suitability of various types of fire detection system in various parts of high rise hotel., content: 'In accordance to UBBL and Bomba department, hotel in Malaysia shall be equipped with appropriate fir...'),
 Document(id=Fan Cooling System Using PLC, HMI and OPC UA, content: 'In today’s globalized world, advancement in technology has made our life more convenient by giving u...'),
 Document(id=The Effectiveness of ESG Communication by Malaysia Airports Holdings Berhad, content: 'Environmental, Social, and Governance (ESG) communication plays a critical role in shaping stakehold...'),
 Document(id=Local Chinese Films in the Malaysian Market: Challenges and Opportunities, content: 'This research investigates the landscape of Chinese films in the Malaysian market, analyzing their v...'),
 Document(id=Antioxidant Potential of Sencha and Hojicha in Tea Bags and Tea Leaves, content: 'Tea with scientific name Camellia sinensis is the second most consumed beverage worldwide next to wa...'),
 Document(id=Gothical Arche, content: ''GOTHICAL ARCHE', the gorgeous gothic architecture, recognized for its ornate motifs and dark colour...'),
 Document(id=The Effect of 6 Weeks Short Foot Exercise on Balance, Sprinting Time, Toe Gripping Force and Force Area among Collegiate Basketball Players, content: 'The purpose of this study was to examine the effects of 6 weeks of short foot exercise on balance, s...'),
 Document(id=The Effectiveness of Instagram Influencers on Purchase Intention of Skincare Products Among Generation Z, content: 'Instagram has emerged as the leading social media platform in the age of digital technology, hence i...'),
 Document(id=The Achievement of Building’s Energy Efficiency by Interior Design, content: 'Malaysia is a developing country and the population and economy of the country is in the uptrend now...'),
 Document(id=Isolation and Identification of L-Methioninase Producing Bacteria from Sugarcane Plantation Soil, content: 'L-Methioninase-producing bacteria are commonly found in soil from sugarcane field or paddy field, as...'),
 Document(id=Review on Association Between Nutrition Intake Lifestyles Intervention on Mild Cognitive Impairment in Older Adults, content: 'The early stage of cognitive impairment is termed as mild cognitive impairment (MCI). Cognitive func...'),
 Document(id=The Awareness of Green Concrete among Property Developers in Klang Valley, content: 'Environmental issue has become the global issue and go green is the new trend especially in construc...'),
 Document(id=The Study on the Impact of Advertising Collaborations between Food and Gaming Brands Affecting Purchase Decisions of Malaysians Aged Between 18 to 30, content: 'This study explores the dynamic world of the impact of advertising collaborations between food and g...'),
 Document(id=IoT Based Intelligent Agriculture Monitoring and Controlling System, content: 'Recently, agriculture has become one of the most important growing sectors in Malaysia. However, the...'),
 Document(id=The Gender Stereotype in the Entertainment Reality Game Show and the Perception of the Audiences, content: 'This research is purposely to investigate the gender stereotype in the entertainment reality games s...'),
 Document(id=TAR UC Events Centralized Registration System, content: 'Nowadays, the emerging of Internet of Things (IoT) has provided a more convenient solution for syste...'),
 Document(id=A Comprehensive Review of Potential Growth of Capsule Hotels in Malaysia, content: 'In year 2017, Malaysia ranked 12 internationally for tourism. The government aims to be top 10 touri...'),
 Document(id=Determine and Identify Problems of High-Rise Condominium Overhang in Malaysia, content: 'Property development, also known as the development of real estate, is the process of developing a h...'),
 Document(id=Effects of Acute Nitrate Supplementation and Heat on Cycling Performance, content: 'Many studies have confirmed the positive implication of nitrate supplementation in reducing the cost...'),
 Document(id=Current Developments of Hydantoin-Based Antimicrobial Agents and in Silico Studies on Staphylococcus Aureus Serine Protease SplA (4mvn), content: 'Hydantoin, imidazole-2,4-dione, is a small five membered non aromatic heterocyclic ring used in phar...'),
 Document(id=The Role of Artificial Intelligence (AI) in the Development of Smart and Sustainable Towns, content: 'The purpose of this study is to improve the adoption of AI in the development of smart and sustainab...'),
 Document(id=Electrodeposited Graphene/Silver/Titanium Dioxide Ternary Composites for Supercapacitor Applications, content: 'Supercapacitor (SC) with ternary hybrid composite as electrodes has become prevalent for the improve...'),
 Document(id=Phytochemical Analysis of Star Anise and Clove Ethanolic Extracts, content: 'Star anise (Illicium verum) and clove (Syzygium aromaticum) are the valuable spices that have been e...'),
 Document(id=Face Alignment and Face Muscle Movement Identification Using GAN, content: 'The conventional face recognition algorithms are unable to perform well under pose variations inputs...'),
 Document(id=Cu-Gr-TiO2 Ternary Nanocomposite for the Application of Anticorrosion Coating: Synthesis, Characterisation and Anticorrosion Properties, content: 'In recent years, nanocomposite coatings have attracted increasing attention in anticorrosion applica...'),
 Document(id=Optimization of Callus Induction of Oryza Sativa by Modulation of 2,4-D and Comparative Study of Antioxidant and Anti-Collagenase Activities of Oryza Sativa and Zingiber Offinicale Roscoe Calli, content: 'Rice (Oryza sativa) extracts (RE) are known to be a vital source of antioxidant and anti-aging compo...'),
 Document(id=The Study of Kinematics and Trajectory Planning of 9 DOF Serial Redundant Robotic Manipulator, content: 'space is greater than the dimension of the end effector space. The aim of this project is to propose...'),
 Document(id=Design and Optimization of Automobile Exhaust Muffler, content: 'This research studies an overview of the performance of the double outlet exhaust muffler. The noise...'),
 Document(id=Effects of Warm-Up with Foam Rolling on Sport Performance: a Systematic Review on the Use Of Smooth and Textured Foam Rollers, content: 'Foam Roller (FR) is well-known to be part of pre-rolling that is able to enhance sport performance a...'),
 Document(id=Integrated Workshop Service Booking Marketplace for Workshop Owners via Web Application Platform, content: 'In the present-day setting, workshop owners are reliant on regular and walk-in clients to gain expos...'),
 Document(id=The Future Trend of Malaysia Transportation: Electric Vehicle Mobile Navigation Application, content: 'Under the dual pressure of energy and environment, the world had begun to vigorously develop the ele...'),
 Document(id=Resident’s Satisfaction towards the Gated and Guarded Community in Klang Valley, content: 'In Malaysia, gated and guarded community (GGC) have proliferated in recent years as a result of incr...'),
 Document(id=Economic Growth of Malaysia, content: 'This study investigates the economic growth of Malaysia by examining the influence of key factors on...'),
 Document(id=Homebuyers’ Acceptance and Willingness to Purchase Green Housing in Klang Valley, content: 'The development of housing projects which featured with green concept is considered as the future tr...'),
 Document(id=Product Development of Durian Seed Chips, content: 'Durian seed is a good source of carbohydrates and natural antioxidants. The purpose of this project ...'),
 Document(id=Adopting Drone Technology to Monitor the Construction Progress in Malaysia, content: 'This study will be conducted to analyses the application of drone technology in differentphase of th...'),
 Document(id=Automated Manufacturing System for the Production of Metal Door Frame, content: 'The whole assembly process of the metal door frame currently employs human operators to execute the ...'),
 Document(id=PR Roles in Malaysian NGOs: an Exploratory Study Using Steyn's PR Roles Model, content: 'This study aimed to look into the Malaysian non-governmental organizations (NGOs) public relations p...'),
 Document(id=Fabrication of Silver/Graphene Oxide Nanocomposites for Supercapacitor Applications Using One-Step Electrochemical Deposition Method, content: 'This project proposes the fabrication of Silver/GO binary nanocomposites for supercapacitor applicat...'),
 Document(id=IT Helpdesk System Integrated with Artificial Intelligence in Web Application, content: 'Nowadays there are more and more people started to work from home in order to cope with the pandemic...'),
 Document(id=Generalisation of Lattice Structure Application in Compression, content: 'In this research paper, compressive properties of lattice structure was analysed by using FEA simula...'),
 Document(id=Comparing the Effects of Stable and Unstable Core Training on Balance and Core Endurance among Sedentary Male College Students, content: 'This study was to compare the effects of 6-week stable and unstable core training programme on balan...'),
 Document(id=Autonomous Robotic Arm with Human Interaction Capability, content: 'Although the robot arm has the advantage of flexibly changing the handle task by reprogramming the r...'),
 Document(id=Xanthine Oxidase Inhibitory Activity of Chrysanthemum morifolium, content: 'Gout is caused by the crystallization of uric acid in the joints; the formation of uric acid require...'),
 Document(id=Reward Point Collection System, content: 'The main purpose of this project is to retain the existing users and attract new user in Smart Campu...'),
 Document(id=Smart Controlled Electric Skateboard, content: 'This proposal presents the design and methodology utilized in the creation of an electric skateboard...'),
 Document(id=Effects of Substitution of Wheat Flour Using Amaranth Flour on the Physicochemical Properties and the Sensory Acceptability of Kelp Noodle, content: 'In recent years, the market size of gluten-free products has increased drastically due to the increa...'),
 Document(id=Screening of Selected Herbs for Their Antioxidant and Antimicrobial Properties, content: 'In recent years, there has been more pressure to use natural preservatives in preservation of foods ...'),
 Document(id=The Influence of Celebrity Endorsement in New Balance Advertisements on Malaysia Generation Z's Attitude through Facebook and Instagram Advertising, content: 'With an emphasis on the worlds of Facebook and Instagram advertising, this research explores the tre...'),
 Document(id=Students’ Perceptions of Service Quality in a Private Higher Education Institution (HEI), content: 'Main objective of this dissertation is to measure and compare the perception and satisfaction of stu...'),
 Document(id=Fabricate & Prototype of High Speed Mobile Robot, content: 'Mobile robot has a vase application, such as industrial automated equipment carries, automated cars,...'),

In [19]:
pipeline = (create_w2v(documents, force_embeddings=False)
            # .with_hyde()
            # .with_bm25()
            # .with_evaluator()
            .make())

50it [00:00, 1053.68it/s]

In [21]:
query = "Design of automated and robotic systems"
top_k = 10
results = pipeline.run(data={
    "query": {"query": query, "top_k": top_k}
}, include_outputs_from={"result", "evaluator"})
results

1it [00:00, 2100.30it/s]

{'result': {'documents': [Document(id=Design and Build Delivery Robot, content: 'Design and build a delivery robot that uses GPS technology to navigate effectively and autonomously ...', score: 0.6697127289171143),
   Document(id=Robot Control Interface with Video Feedback for Wireless Camera, content: 'The title of this project is "Robot Control Interface with Video Feed Back for Wireless Camera". Thi...', score: 0.5733347975141693),
   Document(id=Design of an Automated Powder Spray System for Cable Trunk, content: 'Throughout this Final Year Project, the recessed area of the cable trunk is needed to be sprayed by ...', score: 0.5383138688097516),
   Document(id=Design and Development of Low-Cost Wind Powered Motorcycle Mobile Charger, content: 'Smart devices have become an essential that now acts as an extension of oneself that not only connec...', score: 0.5154608565270495),
   Document(id=Disturbance Force Compensation Using Robust Controller in Linear Drive Positioning System, content: 'The milling machine can carry out many types of machining operations such as end milling, thread mil...', score: 0.5111818111584935),
   Document(id=Preliminary Study of the Finite-Set Model Predictive Control for Five-Level Vienna Rectifier, content: 'This project delves into the transformative landscape of renewable energy, with a specific focus on ...', score: 0.4885960381489972),
   Document(id=Identification in the Presence of Speed Bumps through Few-Shot Learning, content: 'Speed bump is one of the major components in traffic management system, function as to slow down the...', score: 0.484047732262706),
   Document(id=Aluminium Can Crusher Machine, content: 'The project is about designing and fabrication of aluminium can crusher machine. The main reason to ...', score: 0.47600267833661813),
   Document(id=Arduino Based Dual-Axis Solar Tracking System, content: 'The project that this paper is presenting is about preparing, building, and testing a powerful solar...', score: 0.4557609296330067),
   Document(id=Effect of 3D Printing Process Parameters on Mechanical Properties of Printed Part, content: '3D printing technologies are the most promising method in the production of functional parts. Althou...', score: 0.4536094127920195)]}}

In [33]:
ground_truth = datasets.filter(pl.col("title").is_in((
    "Robot Control Interface with Video Feedback for Wireless Camera",
    "Design and Build Delivery Robot",
    "Arduino Based Dual-Axis Solar Tracking System",
    "Identification in the Presence of Speed Bumps through Few-Shot Learning",
    "Robot Control Interface with Video Feedback for Wireless Camera",
    "Single-Sample Face Recognition for Attendance Record",
    "Cable Fault Recognition Using Image Analysis Of Phase Resolved Partial Discharge Pattern",
    "Banana Leaf Disease Detection Using Image Processing Methods",
    "Design of an Automated Powder Spray System for Cable Trunk",
    "Design and Develop a Cost-Effective Hydroponics Autodoser System",
)))
ground_truth

shape: (9, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ title                  ┆ abstract               ┆ webpage_url            ┆ document_url          │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ str                    ┆ str                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ Single-Sample Face     ┆ Face recognition       ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Recognition…           ┆ system is wid…         ┆ du.my/18…              ┆ edu.my/18…            │
│ Design of an Automated ┆ Throughout this Final  ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Powder …               ┆ Year Pro…              ┆ du.my/35…              ┆ edu.my/35…            │
│ Design and Develop a   ┆ Hydroponic systems     ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Cost-Effe…             ┆ offer susta…           ┆ du.my/31…              ┆ edu.my/31…            │
│ Arduino Based          ┆ The project that this  ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Dual-Axis Solar …      ┆ paper is…              ┆ du.my/33…              ┆ edu.my/33…            │
│ Design and Build       ┆ Design and build a     ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Delivery Robo…         ┆ delivery ro…           ┆ du.my/31…              ┆ edu.my/31…            │
│ Identification in the  ┆ Speed bump is one of   ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Presence…              ┆ the major…             ┆ du.my/22…              ┆ edu.my/22…            │
│ Banana Leaf Disease    ┆ This paper presents a  ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Detection …            ┆ detectio…              ┆ du.my/14…              ┆ edu.my/14…            │
│ Cable Fault            ┆ Partial Discharge (PD) ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Recognition Using …    ┆ source …               ┆ du.my/23…              ┆ edu.my/23…            │
│ Robot Control          ┆ The title of this      ┆ https://eprints.tarc.e ┆ https://eprints.tarc. │
│ Interface with V…      ┆ project is "…          ┆ du.my/92…              ┆ edu.my/92…            │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [35]:
ground_truth_documents = [Document(id=row["title"], content=row["abstract"]) for row in ground_truth.iter_rows(named=True)]
ground_truth_documents

[Document(id=Single-Sample Face Recognition for Attendance Record, content: 'Face recognition system is widely used in the world; it had made the human live become more convenie...'),
 Document(id=Design of an Automated Powder Spray System for Cable Trunk, content: 'Throughout this Final Year Project, the recessed area of the cable trunk is needed to be sprayed by ...'),
 Document(id=Design and Develop a Cost-Effective Hydroponics Autodoser System, content: 'Hydroponic systems offer sustainable benefits, but manual nutrient dosing methods pose challenges in...'),
 Document(id=Arduino Based Dual-Axis Solar Tracking System, content: 'The project that this paper is presenting is about preparing, building, and testing a powerful solar...'),
 Document(id=Design and Build Delivery Robot, content: 'Design and build a delivery robot that uses GPS technology to navigate effectively and autonomously ...'),
 Document(id=Identification in the Presence of Speed Bumps through Few-Shot Learning, content: 'Speed bump is one of the major components in traffic management system, function as to slow down the...'),
 Document(id=Banana Leaf Disease Detection Using Image Processing Methods, content: 'This paper presents a detection and classification of banana leaf disease in image processing. One o...'),
 Document(id=Cable Fault Recognition Using Image Analysis Of Phase Resolved Partial Discharge Pattern, content: 'Partial Discharge (PD) source classification is vital to diagnose the insulation quality to prevent ...'),
 Document(id=Robot Control Interface with Video Feedback for Wireless Camera, content: 'The title of this project is "Robot Control Interface with Video Feed Back for Wireless Camera". Thi...')]

In [24]:
precision = 5 / 10
precision

0.5

In [25]:
recall = 5 / 9
recall

0.5555555555555556

In [31]:
fallout = (50 - 5) / (50 - 9)
fallout

1.0975609756097562

In [27]:
f = (2 * precision * recall) / (precision + recall)
f

0.5263157894736842

In [29]:
f_b = lambda b: (1 + b ** 2) * (precision * recall) / (b ** 2 * precision + recall)
f_b(2)

0.5434782608695652

In [47]:
recall = DocumentRecallEvaluator(mode=RecallMode.MULTI_HIT)
recall_result = recall.run(
    ground_truth_documents=[ground_truth_documents],
    retrieved_documents=[results["result"]["documents"]]
)
recall_result

{'score': 0.5555555555555556, 'individual_scores': [0.5555555555555556]}

In [40]:
ndcg = DocumentNDCGEvaluator()
ndcg_result = ndcg.run(
    ground_truth_documents=[ground_truth_documents],
    retrieved_documents=[results["result"]["documents"]]
)
ndcg_result

{'score': 0.649969831884453, 'individual_scores': [0.649969831884453]}

In [42]:
map = DocumentMAPEvaluator()
map_result = map.run(
    ground_truth_documents=[ground_truth_documents],
    retrieved_documents=[results["result"]["documents"]]
)
map_result

{'score': 0.8253968253968254, 'individual_scores': [0.8253968253968254]}